site_name: Eddy3D
site_description: 'Develop, Release and Operate Container Apps on AWS.'
site_url: 'https://aws.github.io/copilot-cli/'
repo_name: 'aws/copilot-cli'
repo_url: # 'https://github.com/aws/copilot-cli'
edit_uri: # 
copyright: 'Copyright &copy; 2018-2025 Eddy3D'
docs_dir: 'site/content'
site_dir: 'docs'
extra_css:
  - stylesheets/extra.css
#extra: 

nav:
  - Home: index.md
  - Documentation:
    - Overview: docs/overview.en.md
    - Getting Started:
      - Install Copilot: docs/getting-started/install.en.md
      - (Optional) Verify the installation: docs/getting-started/verify.en.md
      - Deploy your first application: docs/getting-started/first-app-tutorial.en.md
    - Concepts:
      - Overview: docs/concepts/overview.en.md
      - Applications: docs/concepts/applications.en.md
      - Environments: docs/concepts/environments.en.md
      - Services: docs/concepts/services.en.md
      - Jobs: docs/concepts/jobs.en.md
      - Pipelines: docs/concepts/pipelines.en.md
    - Credentials: docs/credentials.en.md
    - Manifest:
      - Overview: docs/manifest/overview.en.md
      - Backend Service: docs/manifest/backend-service.en.md
      - Load Balanced Web Service: docs/manifest/lb-web-service.en.md
      - Request-Driven Web Service: docs/manifest/rd-web-service.en.md
      - Scheduled Job: docs/manifest/scheduled-job.en.md
      - Static Site: docs/manifest/static-site.en.md
      - Worker Service: docs/manifest/worker-service.en.md
      - Environment: docs/manifest/environment.en.md
      - Pipeline: docs/manifest/pipeline.en.md
    - Developing:
      - Additional AWS Resources:
        - Additional Workload Resources: docs/developing/addons/workload.en.md
        - Additional Environment Resources: docs/developing/addons/environment.en.md
        - Uploading Local Artifacts: docs/developing/addons/package.en.md
      - Container Environment Variables: docs/developing/environment-variables.en.md
      - Content Delivery: docs/developing/content-delivery.en.md
      - Custom Environment Resources: docs/developing/custom-environment-resources.en.md
      - Domain: docs/developing/domain.en.md
      - Extend Copilot with Overrides:
        - YAML Patch Overrides: docs/developing/overrides/yamlpatch.md
        - CDK Overrides: docs/developing/overrides/cdk.md
        - Task Definition Overrides: docs/developing/overrides/taskdef-overrides.md
      - Internal Load Balancers: docs/developing/internal-albs.en.md
      - Manifest Environment Variables: docs/developing/manifest-env-var.en.md
      - Observability: docs/developing/observability.en.md
      - Publish/Subscribe: docs/developing/publish-subscribe.en.md
      - Secrets: docs/developing/secrets.en.md
      - Service-to-Service Communication: docs/developing/svc-to-svc-communication.en.md
      - Sidecars: docs/developing/sidecars.en.md
      - Storage: docs/developing/storage.en.md
    - Commands:
      - Getting Started:
        - docs: docs/commands/docs.en.md
        - init: docs/commands/init.en.md
      - Build:
        - app init: docs/commands/app-init.en.md
        - app upgrade: docs/commands/app-upgrade.en.md
        - app delete: docs/commands/app-delete.en.md
        - env init: docs/commands/env-init.en.md
        - env override: docs/commands/env-override.en.md
        - env package: docs/commands/env-package.en.md
        - env delete: docs/commands/env-delete.en.md
        - job init: docs/commands/job-init.en.md
        - job override: docs/commands/job-override.md
        - job package: docs/commands/job-package.en.md
        - job delete: docs/commands/job-delete.en.md
        - svc init: docs/commands/svc-init.en.md
        - svc override: docs/commands/svc-override.en.md
        - svc package: docs/commands/svc-package.en.md
        - svc delete: docs/commands/svc-delete.en.md
        - run local: docs/commands/run-local.en.md
      - Release:
        - env deploy: docs/commands/env-deploy.en.md
        - job deploy: docs/commands/job-deploy.en.md
        - pipeline init: docs/commands/pipeline-init.en.md
        - pipeline deploy: docs/commands/pipeline-deploy.en.md
        - pipeline ls: docs/commands/pipeline-ls.en.md
        - pipeline override: docs/commands/pipeline-override.en.md
        - pipeline show: docs/commands/pipeline-show.en.md
        - pipeline status: docs/commands/pipeline-status.en.md
        - pipeline delete: docs/commands/pipeline-delete.en.md
        - svc deploy: docs/commands/svc-deploy.en.md
        - deploy: docs/commands/deploy.en.md
      - Operate:
        - app ls: docs/commands/app-ls.en.md
        - app show: docs/commands/app-show.en.md
        - env ls: docs/commands/env-ls.en.md
        - env show: docs/commands/env-show.en.md
        - job ls: docs/commands/job-ls.en.md
        - job logs: docs/commands/job-logs.en.md
        - job run: docs/commands/job-run.en.md
        - svc ls: docs/commands/svc-ls.en.md
        - svc show: docs/commands/svc-show.en.md
        - svc status: docs/commands/svc-status.en.md
        - svc logs: docs/commands/svc-logs.en.md
        - svc exec: docs/commands/svc-exec.en.md
        - task run: docs/commands/task-run.en.md
        - task exec: docs/commands/task-exec.en.md
        - task delete: docs/commands/task-delete.en.md
      - Extend:
        - secret init: docs/commands/secret-init.en.md
        - storage init: docs/commands/storage-init.en.md
      - Settings:
        - version: docs/commands/version.en.md
        - completion: docs/commands/completion.en.md
      - All:
        - app delete: docs/commands/app-delete.en.md
        - app init: docs/commands/app-init.en.md
        - app ls: docs/commands/app-ls.en.md
        - app show: docs/commands/app-show.en.md
        - app upgrade: docs/commands/app-upgrade.en.md
        - completion: docs/commands/completion.en.md
        - deploy: docs/commands/deploy.en.md
        - docs: docs/commands/docs.en.md
        - env delete: docs/commands/env-delete.en.md
        - env deploy: docs/commands/env-deploy.en.md
        - env init: docs/commands/env-init.en.md
        - env ls: docs/commands/env-ls.en.md
        - env override: docs/commands/env-override.en.md
        - env package: docs/commands/env-package.en.md
        - env show: docs/commands/env-show.en.md
        - init: docs/commands/init.en.md
        - job delete: docs/commands/job-delete.en.md
        - job deploy: docs/commands/job-deploy.en.md
        - job init: docs/commands/job-init.en.md
        - job logs: docs/commands/job-logs.en.md
        - job ls: docs/commands/job-ls.en.md
        - job override: docs/commands/job-override.md
        - job package: docs/commands/job-package.en.md
        - job run: docs/commands/job-run.en.md
        - pipeline delete: docs/commands/pipeline-delete.en.md
        - pipeline deploy: docs/commands/pipeline-deploy.en.md
        - pipeline init: docs/commands/pipeline-init.en.md
        - pipeline ls: docs/commands/pipeline-ls.en.md
        - pipeline override: docs/commands/pipeline-override.en.md
        - pipeline show: docs/commands/pipeline-show.en.md
        - pipeline status: docs/commands/pipeline-status.en.md
        - run local: docs/commands/run-local.en.md
        - secret init: docs/commands/secret-init.en.md
        - storage init: docs/commands/storage-init.en.md
        - svc delete: docs/commands/svc-delete.en.md
        - svc deploy: docs/commands/svc-deploy.en.md
        - svc exec: docs/commands/svc-exec.en.md
        - svc init: docs/commands/svc-init.en.md
        - svc logs: docs/commands/svc-logs.en.md
        - svc ls: docs/commands/svc-ls.en.md
        - svc override: docs/commands/svc-override.en.md
        - svc package: docs/commands/svc-package.en.md
        - svc show: docs/commands/svc-show.en.md
        - svc status: docs/commands/svc-status.en.md
        - svc pause: docs/commands/svc-pause.en.md
        - svc resume: docs/commands/svc-resume.en.md
        - task delete: docs/commands/task-delete.en.md
        - task exec: docs/commands/task-exec.en.md
        - task run: docs/commands/task-run.en.md
        - version: docs/commands/version.en.md
  - Community:
      - Get Involved: community/get-involved.en.md
      - Guides and Resources: community/guides.en.md
theme:
  name: material
  custom_dir: site/overrides
  font: false
  icon:
    logo: cd/favicon
  favicon: cd/favicon
  language: en
  features:
    - tabs
    - instant
    - navigation.tabs
        - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    primary: white
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off
    #     name: Switch to system preference

markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - site/overrides/.icons

# Plugins
plugins:
  - search
  #- title-casing
  - glightbox
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: US/Eastern
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
      #exclude:
      #    - index.md
      enabled: true
      strict: true
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false
      count_empty_lines: false
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 1
      #ignore_commits: .git-blame-ignore-revs
      exclude:
      #  - index.md
      enabled: true
      enabled_on_serve: false
      strict: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

