site_name: Eddy3D
site_description: 'Airflow and microclimate simulations for Rhino and Grasshopper'
site_url: https://eddy3d.com
# repo_url: https://github.com/Eddy3D-Dev/Eddy3D-Website
# edit_uri: blob/main/docs/
site_author: Patrick Kastner
copyright: >-
  Copyright &copy; 2018-2025 Eddy3D
extra_css:
  - stylesheets/extra.css
#extra: 



nav:
  - Home: index.md
  - Publications: publications.md
  # Case studies are pulled from external repository
  - Case studies:
      - case-studies/README.md
      - Reykjavik model: case-studies/Reykjavik_Iceland/Reykjavik_Iceland_SimulationModel.md
      - Tropical District Masterplan: case-studies/Tropical_District_Masterplan/Tropical_District_Masterplan.md
      - Cornell Tech Extension: "https://cornelltech.eddy3d.com"
      - Brooklyn OTC Map: "https://brooklyn.eddy3d.com"
  - Download: download.md
  - Documentation: "https://docs.eddy3d.com"
  - Support: support.md

theme:
  name: material
  custom_dir: docs/overrides
  #font: false
  logo: assets/cd/favicon.svg
  favicon: assets/cd/favicon.svg
  icon:
    annotation: material/plus-circle
  features:
    - tabs
    - instant
    - navigation.tabs
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    #- navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - announce.dismiss

  palette:
    primary: white
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/link
    #     name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off
    #     name: Switch to system preference

markdown_extensions:
  - md_in_html
  #- pymdownx.blocks.caption
  - attr_list
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  # - mkdocs-video
  - section-index
  - glightbox:
      skip_classes:
        - skip-lightbox
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: US/Eastern
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
      exclude:
        - contact.md
        - download.md
        - index.md
        - support.md
      enabled: true
      strict: true
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts: 
        remove_comments: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false
      count_empty_lines: false
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 1
      #ignore_commits: .git-blame-ignore-revs
      exclude:
        - contact.md
        - download.md
        - index.md
        - support.md
      enabled: true
      enabled_on_serve: false
      strict: true
  - search
  - title-casing
  - bibtex: 
      bib_file: https://raw.githubusercontent.com/SustainableUrbanSystemsLab/SustainableUrbanSystemsLab.github.io/refs/heads/main/_bibliography/papers.bib
      csl_file: https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/american-medical-association-no-url.csl # docs/citation-style-custom.csl
      enable_inline_citations:  true
  - multirepo:
      cleanup: false
      keep_docs_dir: true
      nav_repos:
        - name: Case Studies
          import_url: https://github.com/Eddy3D-Dev/Eddy3D-CaseStudies/?branch=main
          imports: [/*]



