site_name: Eddy3D Documentation
site_url: https://eddy3d-dev.github.io/Eddy3D-Documentation/
repo_url: https://github.com/Eddy3D-Dev/Eddy3D-Documentation/
# edit_uri: blob/main/docs/
site_author: Patrick Kastner
site_description: >-
  This is the Eddy3D documentation.

# Copyright
copyright: Copyright &copy; 2023 - 2024 Eddy3D


theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.svg
  logo: images/android-chrome-192x192.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: custom
    property: umami
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VIP-SMUR
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Patrick-Kastner
    - icon: fontawesome/brands/google-scholar
      link: https://gscholar.patrickkastner.de/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/patrickkastner/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4940-341X

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs

# Plugins
plugins:
  - search
  #- title-casing
  - glightbox
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: US/Eastern
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
      #exclude:
      #    - index.md
      enabled: true
      strict: true
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false
      count_empty_lines: false
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 1
      #ignore_commits: .git-blame-ignore-revs
      exclude:
      #  - index.md
      enabled: true
      enabled_on_serve: true
      strict: true
  - git-committers:
      repository: VIP-SMUR/wiki
      branch: main
      docs_path: docs/
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'


nav:
  - Home:
      - Overview: index.md

